# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_is_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replies',
            new_name='parent',
        ),
    ]
