# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
