# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 16:54
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20171026_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
