# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreport',
            old_name='post',
            new_name='comment',
        ),
    ]
