# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
