# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170914_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
