# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20170927_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
