# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forum_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
