# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20171024_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True),
        ),
    ]
