# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20171024_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, null=True),
        ),
    ]
