# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20170927_1007'),
        ('notifications', '0002_auto_20171006_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
